# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: clase
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
